USE [master]
GO

/****** Object:  Database [UsersForApp]    Script Date: 01.03.2023 18:48:38 ******/
CREATE DATABASE [UsersForApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsersForApp', FILENAME = N'D:\Development Related\Stupid SQL Express 2019\MSSQL15.SQLEXPRESS\MSSQL\DATA\UsersForApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UsersForApp_log', FILENAME = N'D:\Development Related\Stupid SQL Express 2019\MSSQL15.SQLEXPRESS\MSSQL\DATA\UsersForApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsersForApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UsersForApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsersForApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsersForApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsersForApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsersForApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsersForApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsersForApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsersForApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsersForApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsersForApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsersForApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsersForApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsersForApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsersForApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsersForApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UsersForApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsersForApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsersForApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsersForApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsersForApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsersForApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsersForApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UsersForApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UsersForApp] SET  MULTI_USER 
GO

ALTER DATABASE [UsersForApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsersForApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UsersForApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UsersForApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UsersForApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UsersForApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UsersForApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UsersForApp] SET  READ_WRITE 
GO


