//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public string Job { get; set; }
        public string UserType { get; set; }
        public string SecretWord { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
